apiVersion: batch/v1
kind: CronJob
metadata:
  name: minute-cronjob
  annotations:
    'another-autoscaler/start-time': '0,10,20,30,40,50 * * * *'
    'another-autoscaler/stop-time': '5,15,25,35,45,55 * * * *'
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 180
      template:
        spec:
          containers:
            - name: minute-cronjob
              image: busybox:latest
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
