---
apiVersion: v1
kind: Namespace
metadata:
  name: another

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: another-autoscaler
  namespace: another

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: another-autoscaler
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "deployments/scale", "replicasets"]
  verbs: ["get","list","patch","update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: another-autoscaler
roleRef:
  kind: ClusterRole
  name: another-autoscaler
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: another-autoscaler
  namespace: another

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: another-autoscaler
  namespace: another
data:
  LOG_LEVEL: "DEBUG"
  LOG_FORMAT: "JSON"
  CHECK_EVERY: "5"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-autoscaler
  namespace: another
  labels:
    app: another-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: another-autoscaler
  template:
    metadata:
      labels:
        app: another-autoscaler
    spec:
      serviceAccountName: another-autoscaler
      containers:
      - name: another-autoscaler
        image: ghcr.io/dignajar/another-autoscaler:latest # Change the tag for the latest stable version
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: another-autoscaler
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 10001
          runAsGroup: 10001
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi